import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Form from "../components/Form";
import Banner from "../components/Banner";
import WeatherCard from "../components/WeatherCard";

const Quotes: NextPage = () => {
  //this variable makes a req to the get-weather route with a payload
  const quoteData = trpc.useQuery(["quotes.get-quote"]);
  const [quote, setQuote] = useState("");
  useEffect(() => {
    setQuote(quoteData?.data?.response.text);
  }, []);

  return (
    <>
      <Head>
        <title>Quotes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col justify-center p-4">
        <Banner>
          <p>{JSON.stringify(quote)}</p>
        </Banner>

        <Form
          name="Weather"
          api="weather"
          api_id={1}
          description="Get weather reminders whenever you need them"
        />
      </main>
    </>
  );
};

export default Quotes;
