import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import Form from "../components/Form";

const Weather: NextPage = () => {
  const hello = trpc.useQuery([
    "weather.new-cron",
    { text: "from Vince's app", lat: 49.319981, lon: -123.072411 },
  ]);

  return (
    <>
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        {hello.data ? <p>{hello.data.response}</p> : <p>Loading..</p>}
        <Form
          name="Weather"
          description="Get weather reminders whenever you need them"
        />
      </main>
    </>
  );
};

export default Weather;
