import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Form from "../components/Form";
import Banner from "../components/Banner";
import WeatherCard from "../components/WeatherCard";

const Weather: NextPage = () => {
  //this variable makes a req to the new-cron route with a payload
  const weather = trpc.useQuery([
    "weather.get-weather",
    { lat: 49.319981, lon: -123.072411 },
  ]);
  const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone ?? null;

  const weatherData = weather?.data?.response;

  const WeatherInfo = Object.entries(weatherData ?? {}).map(([key, value]) => {
    console.log(key, value);
    return <WeatherCard key={key}>Test</WeatherCard>;
  });

  return (
    <>
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col justify-center p-4">
        <Banner>
          {weather.data ? (
            Object.entries(weatherData ?? {}).map(([key, value]) => {
              console.log(key, value);
              return (
                <WeatherCard key={key}>
                  <p>{JSON.stringify({ key, value })}</p>
                </WeatherCard>
              );
            })
          ) : (
            <p>Loading..</p>
          )}
        </Banner>

        <Form
          name="Weather"
          api="weather"
          api_id={1}
          description="Get weather reminders whenever you need them"
        />
      </main>
    </>
  );
};

export default Weather;
